# Generated by Django 3.2.11 on 2022-01-15 21:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('Hero1', wagtail.core.blocks.StructBlock([('title1', wagtail.core.blocks.CharBlock(default='Title 1', required=False)), ('title2', wagtail.core.blocks.CharBlock(default='Title 2', required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Read more', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Dimensions minimum: 1920x1280px'))])), ('Features1', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Dimensions minimum: 450x475px')), ('title1', wagtail.core.blocks.CharBlock(default='Title 1', required=False)), ('title2', wagtail.core.blocks.CharBlock(default='Title 2', required=False)), ('our_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Read more', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page', required=False)), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Feature text', required=False))])))]))]),
        ),
    ]
