# Generated by Django 3.2.11 on 2022-01-15 23:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('Hero1', wagtail.core.blocks.StructBlock([('title1', wagtail.core.blocks.CharBlock(default='Title 1', required=False)), ('title2', wagtail.core.blocks.CharBlock(default='Title 2', required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Read more', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Dimensions minimum: 1920x1280px'))])), ('Features', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Dimensions minimum: 450x475px')), ('title1', wagtail.core.blocks.CharBlock(default='Title 1', required=False)), ('title2', wagtail.core.blocks.CharBlock(default='Title 2', required=False)), ('our_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Read more', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page', required=False)), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Feature text', required=False))])))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
